services:
  database:
    container_name: "PostgreSQL"
    image: "postgres:12.10-alpine"
    ports:
      - "9001:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
